version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"

volumes:
  redis-data:
  mongo-data:
